### ISSUE TITLE
Move to IPFS organization?

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-sharness-tests#2]
We should probably move this over to the IPFS organization while you can still retain ownership over it. This will make maintenance and organization easier.

**Comment by chriscool** [comment]
Yeah, I agree that it should be moved. As I have been working alone on this and making some disrupting changes (force pushes and such), I thought it was better to keep it under chriscool for now.

By the way I am not sure if I should try to preserve the history of the test scripts. I just did a `cp -a` for now, but I would understand if people preferred that I keep as much as possible the history. 

And if I try to keep the history of the test scripts this could be a disruptive change to the repo.

**Comment by chriscool** [comment]
Done!

**Comment by kalmi** [comment]
Please archive this repo, and maybe add a note to the description that it was moved to go-ipfs/test/sharness. Google returns this first when searching for ipfs sharness.

**Comment by hsanjuan** [comment]
It's on the list to be archived very soon.
